version: '3'

services:
  php:
    container_name: php_site
    build:
      context: ./php
      args:
        - INSTALL_XDEBUG=true
    depends_on:
      - mysql
    links:
      - mysql:mysql
    volumes:
      - "./public_html:/var/www/html:cached"
    environment:
      PHP_IDE_CONFIG: serverName=site

  mysql:
    container_name: mysql_site
    image: mysql:latest
    volumes:
      - "./mysql/.data:/var/lib/mysql"
      - "./mysql/config/my.cnf:/usr/local/etc/mysql/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: symfony

  nginx:
    container_name: nginx_site
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - "./public_html/:/var/www/html"
      - "./nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/logs:/var/log/nginx"
    depends_on:
      - php
    links:
      - php

  phpmyadmin:
    container_name: pma_site
    image: phpmyadmin/phpmyadmin
    depends_on:
     - mysql
    ports:
        - 8081:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql
