twig:
    paths:
        '%kernel.project_dir%/templates': site
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_horizontal_layout.html.twig'
    globals:
        project_name: "site"
        uploads_image_dir: "/uploads/images/"